### PR TITLE
fix(otelllogs): fix disabling otellogs metrics collection

### LINKED ISSUE #2947: otel collector service fails if collector metrics are disabled
**Describe the bug** A clear and concise description of what the bug is.

otel collector service fails if collector is enabled but collector metrics are disabled

**Logs** Logs which can be helpful in investigating the issue.

```
Error: cannot patch "sumologic-sumologic-otelcol-logs-collector" with kind Service: Service "sumologic-sumologic-otelcol-logs-collector" is invalid: spec.ports: Required value
```

**Command used to install/upgrade Collection** Direct command which you used to install/upgrade collection.

**Configuration** Configuration used for Collection e.g. user-values.yaml for helm.
```
otellogs:
  metrics:
    enabled: false
```

**To Reproduce** Steps to reproduce the behavior.

deploy helm chart with enabled otel but disable otel  metrics

**Expected behavior** A clear and concise description of what you expected to happen.

it should deploy with no errors.

**Environment (please complete the following information):**

- **Collection version** (e.g. `helm ls -n sumologic`): 3.3.0
- **Kubernetes version** (e.g. `kubectl version`): 1.24
- **Cloud provider**: aws
- **Others**:

**Anything else do we need to know** Add any other context about the problem here, e.g. issue happens only occasionally.

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/070d6109042ae9e7e3a52fceadc979b88b9af845/deploy/helm/sumologic/templates/logs/collector/otelcol/service.yaml#L1-L17

if .Values.otellogs.metrics.enabled  == false , ports becomes empty.

### PR DESCRIPTION
**Pull request by kasia-kujawa**
fixes #2947

### Checklist

- [ ] Changelog updated or skip changelog label added
- [ ] Documentation updated
- [ ] Template tests added for new features
- [ ] Integration tests added or modified for major features

### CODE REVIEW

**Review by swiatekm-sumo — COMMENTED** [review]
Can we add a test for this, as it already caused a bug?

**Review by sumo-drosiek — APPROVED** [review]

**Comment by kkujawa-sumo** [comment]
> Can we add a test for this, as it already caused a bug?

I added simple test

**Comment by sumo-drosiek** [comment]
Can we check for enabled metrics case as well?

File: tests/integration/features.go [hunk 1]
```diff
@@ -824,3 +824,37 @@ func CheckFluentdEventsInstall(builder *features.FeatureBuilder) *features.Featu
...
+				require.Eventually(t, func() bool {
+					services = terrak8s.ListServices(t, ctxopts.KubectlOptions(ctx), v1.ListOptions{
+						LabelSelector: fmt.Sprintf("app=%s-sumologic-otelcol-logs-collector", releaseName),
+					})
+
+					return len(services) == 1
+				}, waitDuration, tickDuration)
+				return ctx
+			})
+}
```
Comment (sumo-drosiek) [inline tests/integration/features.go:860]: Please make it gennric

```
func checkOtellogsMetricsServiceCount(ctx context.Context, t *testing.T, envConf *envconf.Config, count int) context.Context {
			return func(ctx context.Context, t *testing.T, envConf *envconf.Config) context.Context {
				releaseName := ctxopts.HelmRelease(ctx)
				var services []corev1.Service
				require.Eventually(t, func() bool {
					services = terrak8s.ListServices(t, ctxopts.KubectlOptions(ctx), v1.ListOptions{
						LabelSelector: fmt.Sprintf("app=%s-sumologic-otelcol-logs-collector", releaseName),
					})

					return len(services) == count
				}, waitDuration, tickDuration)
				return ctx
			}
}
```

```suggestion
			checkOtellogsMetricsServiceCount(ctx, t, envConf, 1)
}
```

Comment (kkujawa-sumo) [reply tests/integration/features.go]: I changed tests to template tests

Comment (sumo-drosiek) [reply tests/integration/features.go]: Now there is no changes for features.go :fearful:

Comment (kkujawa-sumo) [reply tests/integration/features.go]: To test if service is available or not and if it has proper form we can use template tests instead of integration tests.
Do you think that integration tests are needed also?

Comment (sumo-drosiek) [reply tests/integration/features.go]: Ou, I misunderstood the context of `template`

I think we can use `template` tests, but in current tests form empty files don't test anything

Could you try if the following snippets are correct?
```
---
# Source: sumologic/templates/logs/collector/otelcol/service.yaml
```

**Comment by kkujawa-sumo** [comment]
@sumo-drosiek @swiatekm-sumo please take a look once again

File: tests/helm/otellogs_metrics_test.go [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+	templatePath := "templates/logs/collector/otelcol/service.yaml"
+	valuesYaml := `
+otellogs:
+  metrics:
+    enabled: false
+`
+	_, err := RenderTemplateFromValuesStringE(t, valuesYaml, templatePath)
+	expectedError := "error while running command: exit status 1; WARNING: Kubernetes configuration file is group-readable. This is insecure. "
+	expectedError += "Location: /var/snap/microk8s/current/credentials/kubelet.config\nError: could not find template templates/logs/collector/otelcol/service.yaml in chart"
+	assert.EqualError(t, err,  expectedError)
```
Comment (swiatekm-sumo) [inline tests/helm/otellogs_metrics_test.go:20]: If you don't want to do this, you can just render all the templates, decode them into 
k8s objects, and then assert that the Service isn't among them.

Comment (kkujawa-sumo) [reply tests/helm/otellogs_metrics_test.go]: Isn't this version simpler?
```
	_, err := RenderTemplateFromValuesStringE(t, valuesYaml, templatePath)
	expectedError := "Error: could not find template templates/logs/collector/otelcol/service.yaml in chart"
	assert.ErrorContains(t, err, expectedError)
```

Comment (swiatekm-sumo) [reply tests/helm/otellogs_metrics_test.go]: It is, I didn't like the previous error assertion, but this one works.

**Review by swiatekm-sumo — APPROVED** [review]
